#coding: utf-8

module Reader
  module ReadCSV
    require 'modules/reader/core'
    include Reader::Core
    
    #For LocStudio CSV generated by CSVDumpW
    def readCSV(file, option)
      file_str = read_rawfile(file)
      ops = {:col_sep => ",", :headers => true, :quote_char => '"'}
      myCSV = CSV.new(file_str, ops)
      myCSV.map {|row|
        entry = {}
        entry[:filename] = file.to_s
        entry[:source]   = row["Source Term"]
        entry[:target]   = row["Translation"]
        entry[:id]       = row["Resource ID"]
        entry[:note]     = row["Term Note"]
        @@bilingualArray.push(entry)
      }
    end
  end
end
