#coding: utf-8

module Reader
  module ReadCSV
    require 'modules/reader/core'
    include Reader::Core

    #For LocStudio CSV generated by CSVDumpW
    def readCSV(file, option)
      file_str = read_rawfile(file)
      #header on / off
      ops = {:col_sep => ",", :headers => false, :quote_char => '"'}
      myCSV = CSV.new(file_str, ops)
      myCSV.map {|row|
        #
        #Filter
        #
        #next unless row[2].start_with?("★")

        entry = {}
        entry[:filename] = file.to_s

        #Use this to specify columns by number
        entry[:source]   = row[2]
        entry[:target]   = row[3]
        entry[:id]       = row[1]

        #Use this to specify columns by header
        #entry[:source]   = row["Source Term"]
        #entry[:target]   = row["Translation"]
        #entry[:id]       = row["Resource ID"]
        #entry[:note]     = row["Term Note"]
        @@bilingualArray.push(entry)
      }
    end
  end
end
