required:
  bilingual: A:\!Projects\_SST\120430_ADAPL_1204_035\06_FromQA\120510_hayakawa\unclean
  output: C:\Documents and Settings\ayumu.hanba\デスクトップ\lab\zzzzz
  report: xls
  source: EN
  target: JA
  glossary: C:\z_hiatus\!g
  monolingual: C:\Documents and Settings\ayumu.hanba\デスクトップ\lab\zzzzz\!work\test

check:
  glossary: false
  inconsistency_s2t: true
  inconsistency_t2s: true
  missingtag: true
  skip: true
  monolingual: true
  numbers: true
  unsourced: true
  unsourced_rev: false
  length: false
  
option:
  filter_by: 
  ignore100: false
  ignoreICE: false
