required:
  bilingual: C:\z_hiatus\!bi
  output: C:\z_hiatus
  report: xls
  source: EN
  target: JA
  glossary: C:\z_hiatus\!g
  monolingual: C:\z_hiatus\!m

check:
  glossary: true
  inconsistency_s2t: true
  inconsistency_t2s: true
  missingtag: true
  skip: true
  monolingual: true
  numbers: true
  unsourced: true
  length: false
  
option:
  filter_by: 
  ignore100: false
