required:
  bilingual: C:\Users\User\Desktop\hiatus\__sample\!b
  output: C:\Users\User\Desktop\hiatus
  report: xls
  source: EN
  target: JA
  glossary: C:\Users\User\Desktop\hiatus\_sample\!gloss
  monolingual: C:\Users\User\Desktop\hiatus\_sample\!mono

check:
  glossary: true
  inconsistency_s2t: true
  inconsistency_t2s: true
  missingtag: true
  skip: true
  monolingual: true
  numbers: true
  unsourced: true
  unsourced_rev: false
  length: true
  
option:
  filter_by: 
  ignore100: false
  ignoreICE: false
